# Generated by Django 5.2.1 on 2025-06-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_phone_number_alter_user_user_type_ticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('TECH', 'Technician'), ('EMP', 'Employee')], default='EMP', max_length=10),
        ),
    ]
