# Generated by Django 5.2.1 on 2025-06-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Technician', 'Technician'), ('Employee', 'Employee')], default='Employee', max_length=20),
        ),
    ]
