# Generated by Django 5.2.1 on 2025-06-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TECH', 'Technician'), ('EMP', 'Employee')], default='EMP', max_length=10),
        ),
    ]
