# Generated by Django 5.2.1 on 2025-06-15 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdes', '0004_department_is_active_alter_department_name'),
        ('knowledgebase', '0004_alter_knowledgebasearticle_related_ticket_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='ticketcomment',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='ticketstatuschange',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='ticketcategory',
            name='default_assignee',
        ),
        migrations.RemoveField(
            model_name='ticketcomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='ticketstatuschange',
            name='changed_by',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='TicketCategory',
        ),
        migrations.DeleteModel(
            name='TicketComment',
        ),
        migrations.DeleteModel(
            name='TicketStatusChange',
        ),
    ]
