# Generated by Django 5.2.1 on 2025-06-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0003_alter_knowledgebasearticle_author_and_more'),
        ('tickets', '0005_ticketcategory_ticketstatuschange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebasearticle',
            name='related_ticket_categories',
            field=models.ManyToManyField(blank=True, to='tickets.ticketcategory'),
        ),
    ]
