# Generated by Django 5.2.1 on 2025-06-12 08:58
from django.db import migrations, models
import uuid

def generate_unique_reference():
    return f"TCK-{uuid.uuid4().hex[:6].upper()}"

def populate_reference_numbers(apps, schema_editor):
    Ticket = apps.get_model('tickets', 'Ticket')
    for ticket in Ticket.objects.all():
        if not ticket.reference_number:
            ticket.reference_number = generate_unique_reference()
            # Ensure no duplicates exist
            while Ticket.objects.exclude(pk=ticket.pk).filter(reference_number=ticket.reference_number).exists():
                ticket.reference_number = generate_unique_reference()
            ticket.save(update_fields=['reference_number'])

class Migration(migrations.Migration):
    dependencies = [
        ('tickets', '0002_department_ticket_attachment_ticket_closed_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='ticketcomment',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='ticket',
            name='reference_number',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True),
        ),
        migrations.RunPython(
            populate_reference_numbers,
            reverse_code=migrations.RunPython.noop  # No reverse operation needed
        ),
    ]