# Generated by Django 5.2.1 on 2025-06-15 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticketcategory_ticketstatuschange'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='default_assignee',
            field=models.ForeignKey(blank=True, help_text='Optional: Assign a default technician to handle tickets in this category.', limit_choices_to={'role': 'admin,technician'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.category'),
        ),
    ]
